davidrg/ckwin

.github/workflows/build.yml, setenv.bat
=> Automated builds via github actions

.github/workflows/build.yml, .gitignore, README.md, clean.bat, doc/changes.md, doc/optional-dependencies.md, kermit/k95/ck_des.c, kermit/k95/ckoath.c, kermit/k95/ckoker.mak, kermit/k95/ckuath.c, kermit/k95/feature_flags.mak, kermit/k95/mkdist.bat, libdes/clean.bat, libdes/libdes.mak, libdes/mknt.bat, setenv.bat
Not because its useful, but because Kermit 95 had it and fixing/adding this means one less feature missing from CKW.
=> K95crypt - support for the Telnet Encryption Option (DES/CAST)

kermit/k95/ckoshs.c
Fix hang when connecting with NONE authentication, closes https://github.com/davidrg/ckwin/issues/145
=> Fix connecting with NONE authentication

.github/workflows/build.yml, .gitignore, kermit/dialer/clean.bat, kermit/dialer/dialetc.c, kermit/dialer/k95dial.mak, kermit/dialer/kconnect.cpp, kermit/dialer/main.cpp, kermit/dialer/mk.bat, kermit/dialer/mkdist-os2.bat, kermit/dialer/mkdist.cmd, kermit/dialer/mkos2.bat, kermit/dialer/mkos2.cmd, kermit/k95/ckoker.mak, kermit/k95/k2.ini, kermit/k95/mkdist-os2.bat, mkzinc.bat, setenv.bat, setenv.cmd
=> Support for building the Dialer with OpenWatcom for OS/2

.github/workflows/build.yml
As well as OpenSSL if possible.
=> Use Jom instead of nmake for building libdes and ckw itself

doc/changes.md, kermit/k95/ckoco3.c, kermit/k95/ckuusr.h
This is actually a VT420 feature and we already support a few other VT420 features under the VT320 emulation profile so no reason this can't go out now.
=> Cherrypick DECRQCRA from the xterm-emu branch

README.md, doc/changes.md, doc/ssh-readme.md, kermit/k95/ckolssh.c, kermit/k95/ckolsshs.c, kermit/k95/ckolsshs.h, kermit/k95/ckonssh.c, kermit/k95/ckorbf.c, kermit/k95/ckorbf.h, kermit/k95/ckossh.c, kermit/k95/ckossh.h, kermit/k95/ckuus3.c, kermit/k95/ckuusr.c
=> SSH Local and remote port forwarding!

.github/workflows/build.yml, .gitignore, doc/changes.md, kermit/k95/Makefile, kermit/k95/ckcdeb.h, kermit/k95/ckoker.mak, kermit/k95/ckotio.c, kermit/k95/ckuus3.c, kermit/k95/ckuus5.c, kermit/k95/compiler_detect.mak, kermit/k95/feature_flags.mak, kermit/k95/mkdist.bat, setenv.bat
=> Support for REXX on Windows

kermit/dialer/k95dial.mak, kermit/k95/ckoker.mak, kermit/k95/compiler_detect.mak, kermit/p95/mknt.bat
this make file should handle all platforms
=> generalize use of compiler_detect.mak file

kermit/k95/compiler_detect.mak, setenv.bat, setenv.cmd
now it call Open Watcom C compiler to check if Open Watcom is available (configured)
To detect version use compiler banner text which contains Open Watcom version
=> add "true" Open Watcom check for version 1.9 and 2.0

doc/changes.md, kermit/k95/ckolssh.c, kermit/k95/ckonet.c, kermit/k95/ckonssh.c, kermit/k95/ckossh.c, kermit/k95/ckossh.h, kermit/k95/k95custom.ini
And restore the previous default for user known hosts Fixes #350
=> Set a default value for global known hosts

kermit/dialer/k95dial.mak, kermit/dialer/registry/registry.mak, kermit/dialer/setup/setup.mak, kermit/k95/ckoker.mak, kermit/k95/kui/makefile, kermit/p95/p2.mak, kermit/p95/p95.mak
correct make files for debug builds to match compiler and linker options
=> build: correct make files for open watcom

kermit/dialer/k95dial.mak, kermit/dialer/registry/registry.mak, kermit/k95/ckoker.mak, kermit/k95/kui/makefile, kermit/p95/p95.mak, setenv.bat
add -dWINVER=0x0400 to fix Open Watcm issue with Windows header files
=> cleanup: cleanup several make files issues related to resource compile

kermit/k95/ckoco3.c, kermit/k95/p.h, kermit/k95/p_type.h, kermit/k95/setup.c, kermit/k95/textps.c, kermit/p95/pdll_async.h, kermit/p95/pdll_global.c, kermit/p95/pdll_main.c, kermit/p95/pdll_socket.h
add missing references to standard C headers
=> correct various type mismatches

.github/workflows/build.yml
add installation to mingw cross-compile
=> fix perl modules installation

.github/actions/cache/action.yml, .github/workflows/build.yml
composite action cannot use vars context
it must be passed as input parameter from main workflow
remove redundant use of vars.NOCACHE
=> fix NOCACHE variable processing

.github/actions/load-vs2003/action.yml, .github/workflows/build.yml
consolidate code and use matrix for Open Watcom build that more build variants is possible
=> consolidate Open Watcom workflow code

.github/workflows/build.yml
limited permission is changed only for website deployment job not for all jobs
=> build: fix incorrect permission for build

setenv.bat, srp/krypto.mak, srp/srp.mak, srp/tconf.mak
Some change at some point broke the libsrp build.
=> Try to fix the SRP build

doc/changes.md, doc/manual/k95bugs.html, kermit/k95/ckcfn2.c, kermit/k95/ckcfns.c, kermit/k95/ckcmai.c, kermit/k95/ckcpro.c, kermit/k95/ckcpro.w, kermit/k95/ckofio.c, kermit/k95/ckosyn.c, kermit/k95/ckosyn.h, kermit/k95/ckotio.c, kermit/k95/ckuusx.c
No more press Ctrl+C to Crash! This one was a real pain to track down. Fixes #99
=> Fix Autodownload crashing on Ctrl+C

doc/changes.md, doc/ctlseqs.xml, doc/manual/setterm.html, kermit/k95/ckcker.h, kermit/k95/cknwin.c, kermit/k95/ckoco3.c, kermit/k95/ckocon.c, kermit/k95/ckuus2.c, kermit/k95/ckuus3.c, kermit/k95/ckuus5.c, kermit/k95/ckuus7.c
Which also means we now support xterm private mode 1042
=> Option to flash the window on bell

.github/workflows/build.yml, doc/changes.md, doc/manual/rexx.html, rexx/README.md, rexx/arm32.patch
=> REXX for ARM32
