davidrg/ckwin

.github/workflows/build.yml
kermit/k95/ckoker.mak
kermit/k95/kui/makefile

This is the earliest freely available version of Visual C++. Goal is simply to prevent accidentally breaking older compilers - if they break it should be because support has been intentionally dropped, which it has not yet.
This is branched off of and going back in to the ssh branch due to the scope of makefile changes that have been made there (doing it on master would make for difficult merging later)

Build with Visual C++ 2003 Toolkit

---

.github/workflows/build.yml
doc/optional-dependencies.md
kermit/k95/ck_ssl.c
kermit/k95/ck_ssl.h
kermit/k95/ckcdeb.h
kermit/k95/ckoath.c
kermit/k95/ckoker.mak
kermit/k95/ckossl.c
kermit/k95/feature_flags.mak
kermit/k95/mkdist.bat
setenv.bat

Now builds and appears to work with OpenSSL 0.9.8zf, 1.0.0s, 1.0.1u, 1.1.0l and 1.1.1q. Builds with OpenSSL 3.0.4 too though HTTPS connections don't work for some reason

Restore OpenSSL support

---

kermit/k95/ckoker.mak
kermit/k95/mkos2.bat

And also make sure mkos2.bat reports errors when the build fails.

Fix OS/2 cross-compile failure

---

.github/workflows/build.yml

This includes the Visual C++ 2010 compiler which is the last that can target Itanium and is new enough to still be supported by OpenSSL 1.1.1 (though its not new enough to be supported by libssh)

Build for Itanium with the Windows 7 Platform SDK version 7.1

---

.github/workflows/build.yml
doc/code-index.md

Some build options, like SRP, are basically never tested due to the age and support status of the required dependencies.
This PR is add SRP and other rarely tested things to CI to ensure these build options don't get broken accidentally. This is to ensure they remain available to anyone who may need them despite the known security issues, and to ensure the existing code remains buildable in case someone wants to take on the task of porting the related code to newer alternatives (replace libsrp with OpenSSL, replace K4W with Heimdal, etc)

Build with legacy dependencies

---

.github/workflows/build.yml
kermit/k95/mkdist.sh

There isn't any make-distribution script for cross-builds from UNIX. Move the current script out of github actions so it can be run in the same way as you would for Windows.
Also this script doesn't currently collect runtime libraries which it really should. Make it do that.

Move mkdist script out of GH Actions workflow

---

.github/workflows/build.yml

This may well be the final OpenSSL 1.1.1 release given its going out of support on the 11th of September.

Update to OpenSSL 1.1.1v

---

.github/workflows/build.yml

Check local changes to shared modules (cku* and ckc*) are still compatible with C-Kermit for Linux by grabbing the matching unmodified Linux code and substituting in our local modified versions of these files.

Linux check build

---

.github/workflows/build.yml

Upgrade to the latest versions of OpenSSL 3.0 and libssh 0.10

Upgrade to OpenSSL 3.0.12 and libssh 0.10.6

---

doc/changes.md
kermit/k95/ckocon.h
kermit/k95/kui/kclient.hxx
kermit/k95/kui/ksysmets.cxx

In K95G only, doubles max width to 512 columns and increases the max window size to be that of the virtual screen rather than the primary screen on windows versions that support this.

Increase max terminal dimensions

---

.github/workflows/build.yml
doc/changes.md

Looks like the subsystem version on openssl.exe is being marked too high rendering it incompatible with XP.

Try fix openssl.exe not working on XP

---

.github/workflows/build.yml
kermit/k95/ckoker.mak
kermit/k95/kui/makefile
kermit/k95/mkdist.bat

To make debugging easier, include PDB files in release builds where it is practical to do so.

Include PDB files with release builds

---

.github/workflows/build.yml
doc/changes.md

Released on 3 September 2024, this is a security and bug fix

Upgrade to OpenSSL 3.0.15

---

.github/workflows/build.yml

simplify use of OpenWatcom for Kermit build (Github Actions) and enable configuration for various versions and target

add use OpenWatcom-setup repository for OpenWatcom build

---

kermit/dialer/k95dial.mak
kermit/k95/ckoker.mak

remove useless -x option, OW linker do case-sensitive linking by default -bt option must be os2 for both 16-bit and 32-bit
difference is in linking target 16-bit target use -l=os2 and 32-bit target use -l=os2v2

update OW tools used options

---

kermit/dialer/k95dial.mak
kermit/k95/ckoker.mak
kermit/k95/compiler_detect.mak
kermit/k95/feature_flags.mak

use the -bd option to compile for the DLL
use -br option to compile with DLL version of C/C++ runtimes, doesn't assume it to be DLL, can be used for EXE or DLL format.
Add extra macros LINKFLAGS_WIN (GUI application) and LINKFLAGS_DLL (DLL) for linking
LINKFLAG is used for Character mode application
Use 
OWCL for Microsoft CL clone
and 
OWWCL for Open Watcom Compile and Link utility (WCL)

Correct build DLLs for OS/2 by Open Watcom

---

kermit/k95/ckcmai.c
kermit/k95/ckuusx.c

correct missing prototype for getpid function

---

kermit/dialer/kconnect.cpp
kermit/k95/cknalm.c
kermit/k95/ckntap.c
kermit/k95/cknwin.c
kermit/k95/ckoclip.c
kermit/k95/ckocon.c
kermit/k95/ckomou.c
kermit/k95/ckonet.c
kermit/k95/ckoreg.c
kermit/k95/ckothr.c
kermit/k95/ckotio.c
kermit/k95/iksdsvc.c

remove incorrect calling convention for ExecuteBrowser
it is used as thread start function and should use default calling convention

correct type mismatches for _beginthread calls

---

.github/workflows/build.yml
kermit/k95/ckoker.mak
kermit/k95/kui/makefile
kermit/k95/mkdist-os2.bat
kermit/k95/mkdist.bat
kermit/p95/p95.mak
libdes/libdes.mak
setenv.bat
srp/krypto.mak
srp/srp.mak
srp/tconf.mak

not used now, static C/C++ run-time libraries are used now

Fix handling of Open Watcom DLL C/C++ run-time libraries

---

kermit/dialer/mkos2.bat
kermit/dialer/mkos2.cmd
kermit/k95/mkos2.bat
kermit/k95/mkos2.cmd
kermit/k95/mkos2d.bat
kermit/k95/mkos2d.cmd

remove hardcoded library search path for OS/2
it is handled by OW linker

cleanup OS/2 build batch files

---

kermit/dialer/k95dial.mak
kermit/dialer/registry/registry.mak
kermit/dialer/setup/setup.mak
kermit/k95/kui/makefile

this option is not supported by any version of Watcom or Open Watcom

build: remove /noBool option for Watcom and Open Watcom

---

kermit/k95/ckoker.mak
kermit/k95/kui/makefile

this option is not supported by any version of Watcom or Open Watcom

build: remove /GA option for Watcom and Open Watcom

---

kermit/k95/ckoco2.c
kermit/k95/ckoco3.c
kermit/k95/ckofio.c
kermit/k95/ckop.c
kermit/k95/ckotvi.c
kermit/k95/ckuus3.c
kermit/k95/ckuus5.c
kermit/k95/ckuusr.c
kermit/k95/textps.c

correct missing int type (K&R default, not permitted by newer standards)

add missing types

---

kermit/k95/ckonssh.c
kermit/k95/ckop.c
kermit/k95/ckop.h
kermit/k95/ckossh.c
kermit/k95/ckossh.h
kermit/k95/p.h
kermit/k95/p_callbk.c
kermit/k95/p_callbk.h
kermit/k95/p_type.h
kermit/p95/pdll_main.c

now appropriate macros with calling convention is used
no manipulation with _System calling convention which is incorrect (OS API use it in header files)
it enable define calling convention consistently
Anyway I think that CKDEVAPI can be any fixed calling convention by example cdecl for better interoperatibility
_System is not required.
if CKDEVAPI is blank then compiler default calling convention is used therefore you cannot combine DLL build by one compiler with Kermit build by another one, it depend on default calling convention.
simply 
`
#define CKDEVAPI cdecl
`
ensure interoperability, all compilers will use cdecl calling convention.

correct use of _System calling convention

---

kermit/k95/ckoker.mak
kermit/k95/ckolssh.c
kermit/k95/ckonssh.c
kermit/k95/ckossh.c
kermit/k95/ckossh.h
kermit/k95/k95ssh.def
kermit/k95/nullssh.def

- only layer on Kermit side (ckossh.c) was defined but the same layer must be present on DLL side (ckolssh.c or ckonssh.c) to work properly with different compilers
- 64-bit Windows has defined ABI for DLL that default calling convention is used
- 32-bit systems has not defined ABI for DLL therefore any calling convention can be used, to simplify it cdecl calling convention is used for all 32-bit platforms, it enable to use DLL by any other compiler without dependency on compiler default calling convention
- fix prototypes to use (void) if no parameters are passed, K&R syntax () means any parameters, newer C standards don't permit mixing with K&R syntax and it is reported by some compilers as parameter passing issue
- the DLL export of the ssh_impl_ver function has been removed because no …

fix issues with calling convention in Kermit SSH DLL

---

kermit/k95/ckoker.mak

"Command list does not belong to any target"

build: add default object file extension to suppress message

---

kermit/k95/ckoker.mak

increase stack size to be same as for console application

build: correct OS/2 stack size for Presentation Manager applications

---

kermit/k95/mkdist.bat
kermit/k95/mkg.bat
kermit/k95/mkiksd.bat
kermit/k95/mkkui.bat
kermit/k95/mknt.bat
kermit/k95/mkntd.bat
kermit/k95/mkos2.bat
kermit/k95/mkos2d.bat
kermit/k95/mkos2d.cmd
kermit/k95/mksshdll.bat

all *.pdb must be handled conditionaly because Open Watcom doesn't use it also if subdirectory is created conditionaly then files in this subdirectory must be processed conditionaly all deletes must be also conditionaly handled

build: cleanup build make and batch files

---

.github/workflows/build.yml
doc/changes.md

OpenSSL 3.4 is the version that has the longest support horizon at this point (at least until the next LTS release which will probably be 3.5).
Tested fine on Windows XP SP3 and ARM32 Windows 8.1. Not tested on Itanium but earlier releases worked so I'll just have to assume this does too (no access to hardware)

Upgrade to OpenSSL 3.4

---

kermit/k95/ck_crp.c
kermit/k95/ckoath.c
kermit/k95/ckolssh.c
kermit/k95/ckonssh.c
kermit/k95/ckossh.c
kermit/k95/ckossh.h
kermit/k95/ckuat2.h

renaming vscrnprintf to scrnprint to make the difference from Vscrnprintf transparent
using a single argument and removing the variadic type of the function (to improve portability between compilers and calling conventions)

fix issue with vscrnprintf type

---

kermit/k95/ckoath.c

all pointers in crypt DLL use default calling convention now including OS/2
therefore pointers cast for OS/2 must be same as for other host OS (now only NT)
Open Watcom compiler properly report it as calling convention mismatch (_System versus default calling convention)
now I fixed only mismatch between default calling convention and cast to _System which is wrong (mismatch)
I will fix later crypt DLL calling convention to be well defined and not relate to default calling convention

fix incorrect function pointers cast for OS/2 target

---

kermit/k95/ck_crp.c
kermit/k95/ck_des.c
kermit/k95/ckoath.c
kermit/k95/ckolssh.c
kermit/k95/ckonssh.c
kermit/k95/ckossh.c
kermit/k95/ckossh.h
kermit/k95/ckuat2.h

rename symbols for SSH and CRYPT DLL initialization code to be consistent over both projects

rename some symbols to be more consistent

---

.github/workflows/build.yml

in latest Windows SDK 10.0.26100.0 is not included 32-bit ARM files 
latest SDK which contains 32-bit ARM files is 10.0.22621.0

arm-build: temporary fix 32-bit ARM build

---

.github/actions/cache/action.yml
.github/workflows/build.yml

It is useful for debugging CI-build
it simply doesn't use cache and cache is hold untouched

add repository variable NOCACHE to disable CI-build caching

---

.github/workflows/build.yml

These variables contain current architecture value to simplify scripts

add CK_OPENSSL_VARIABLE and CK_K4W_PATH environment variables

---

.github/actions/cache/action.yml
.github/actions/files-check/action.yml
.github/actions/load-openzinc/action.yml
.github/actions/load-tools/action.yml
.github/actions/load-vs2003/action.yml
.github/actions/load-vs2010/action.yml
.github/actions/load-watcom/action.yml
.github/workflows/build.yml
openssl/setargv.c

composite action do all necessary steps transparent way
- composite action for cache/get/setup build MSVC compilers
- composite action for cache/get/setup Open Watcom
- composite action for cache/get/setup Open Zinc
- composite action for cache/get/setup build Tools (nasm+jom+info-zip+os2tk45)
- composite action for check existence of created distribution files
- fix bug in VCT2003 downloaded image, missing setargv.obj file for x86 target
- use Visual studio numbering instead of Visual C++ compiler Toolkit numbering
- fix for arm version build by VS2019 and VS2022, it is necessary select appropriate runner Windows image containing correct Visual Studio version

add new local composite actions to simplify workflow script

---

.github/workflows/build.yml
README.md
doc/web/index.html

This _should_ maintain two versions of the manual on github pages:
* The manual for the latest "stable" release (which is really beta 7 right now). This is either downloaded from the previous version of the github pages site and added in to the new version, or its pulled from an asset attached to the latest release on github
* The manual for the current development code in the git master branch
There is also a little index page with some information and other pointers.

Publish the manual to github pages

---

doc/changes.md
doc/ctlseqs.xml
doc/manual/setterm.html
kermit/k95/ckoco3.c
kermit/k95/ckoco4.c
kermit/k95/ckocon.h
kermit/k95/ckoker.mak
kermit/k95/ckotio.c
kermit/k95/ckuus2.c
kermit/k95/ckuus5.c
kermit/k95/ckuus7.c
kermit/k95/ckuusr.h
kermit/k95/feature_flags.mak
kermit/k95/kui/ikui.cxx
kermit/k95/kui/ikui.h
kermit/k95/kui/kappwin.cxx
kermit/k95/kui/kappwin.hxx
kermit/k95/kui/ktermin.cxx
kermit/k95/kui/kui.rc

This allows both querying (reading) the clipboard, and setting (writing) it, translating to/from the remote character set as required.
The feature is off by default, and can be enabled in one or both directions via SET TERMINAL CLIPBOARD-ACCESS. In K95G, when the remote host uses OSC-52 you can optionally choose to receive a notification on Windows 2000 or up.

Implement OSC-52

---

.github/workflows/build.yml
kermit/k95/ckover.h

This changes the build workflow to produce Windows XP-compatible builds using the windows-2022 runnner, the 14.29 toolset and an older Windows SDK. This should allow the unified Windows XP-Windows 11 builds to keep going for a little while longer, though it is feeling like it won't be long now before Windows XP has to be split out on its own.

Fix Windows XP builds

---

doc/changes.md
kermit/k95/ckolssh.c

This change increases throughput by around 7x for terminal sessions over SSH. This primarily means K95 now handles you accidentally `cat`ting a large log file a little better. It should now be able to handle around 2MB/s where as previously it was around 275KB/s.
This is achieved by a change to `ssh_inc`, the function for reading a single character from the connection. This previously would read a single character from the ring buffer with all the mutex wrangling that comes with it.
Now `ssh_inc` has its own little buffer which *isn't* protected with mutexes. When `ssh_inc` is called, if its buffer is empty and one or more characters are waiting in the ring buffer it will pull up to 1K out of the ring buffer into its local buffer. It will then return characters from its local buffer until …

Improve throughput for terminal sessions over SSH

---

doc/changes.md
kermit/k95/ckocon.h

This is really just an interim solution to enable K95G to render properly on an unscaled 4K display. Eventually some work needs to be done to decouple memory use from the maximum dimensions by allocating various data structures dynamically, but thats not work that is likely to happen in the near future.

Double maximum terminal lines to 256 on modern K95G
